### ISSUE TITLE
Not allowed to load local resource:

### ISSUE THREAD

**Issue by shitanshu7eye** [pamtbaau/electron-angular-sqlite-bootstrap-webpack#7]
Not allowed to load local resource:
![Screenshot_13](https://user-images.githubusercontent.com/34265477/60500393-e11a2700-9cd7-11e9-890a-f0005a26414a.png)

**Comment by pamtbaau** [comment]
Just a suggestion... If you would like someone to spend time on your issue, it might help to spend a bit more time on it yourself...

Make sure the file mentioned does exist. When I rename the /path/to/dist/index.html, the same error is thrown. Other then that, the app works fine out of the box.
